### ISSUE TITLE
API Error while register

### ISSUE THREAD

**Issue by belgio99** [belgio99/smartfactory#104]
Right now register is broken because of this. The error is most likely from the hash_data function:

https://github.com/belgio99/smartfactory/blob/eac70e3054822b6cb065a155826213e9ff71f22a/api/src/app.py#L49-L54

Traceback
```
ERROR:root:Exception: can only concatenate tuple (not "str") to tuple
INFO:     172.29.0.6:44178 - "POST /smartfactory/register HTTP/1.1" 500 Internal Server Error
```

**Comment by Alexthw46** [comment]
Just to not forget, while the register now work, we get the hashed username instead of the username given!
We might simply be able to use  the name set in user settings, and perhaps we should, but  the odd thing is that the role is hashed too...
