### ISSUE TITLE
KB container crashing at startup

### ISSUE THREAD

**Issue by belgio99** [belgio99/smartfactory#17]
No logs for you guys unfortunately, but container isn't starting!

Exit code is 0 so I think it's not doing anything and just quitting. Check uvicorn, kb.py and file paths!

**Comment by JacopoRaffi** [comment]
The problem is just that in the "main" function we didn't start uvicorn. I don't know if we can close this issue(?)

**Comment by belgio99** [comment]
Nope guys, still same thing as before. Crashing with exit code 0
