### ISSUE TITLE
GUI not loading anymore

### ISSUE THREAD

**Issue by belgio99** [belgio99/smartfactory#58]
Traceback below: probably the error is "`Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/bcryptjs/dist'`"?

```
Starting the development server...
Compiled with warnings.
Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/bcryptjs/dist'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }
Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
WARNING in ./node_modules/bcryptjs/dist/bcrypt.js 64:13-45
Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/bcryptjs/dist'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }
webpack compiled with 1 warning
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
No issues found.
```

**Comment by Degik** [comment]
When you try to make the build to run this command "npm install"?

**Comment by belgio99** [comment]
I can't run this because I just deploy the images, if it's needed to build the app you have to put it in the Dockerfile of gui-panel

**Comment by Degik** [comment]
https://github.com/belgio99/smartfactory/blob/main/gui-panel/Dockerfile

There's, but I don't know why he didn't work, cause in local I don't have any problem

**Comment by Degik** [comment]
Otherwise is not beautiful, but we can try to upload the entire node-modules folder

**Comment by Alexthw46** [comment]
I'm trying with the -browserify approach. The error doesn't lock you from compiling tho, we have it in our envs but everything works? Could it be another issue the real deal

**Comment by Degik** [comment]
> I'm trying with the -browserify approach. The error doesn't lock you from compiling tho, we have it in our envs but everything works? Could it be another issue the real deal

Same opinion

**Comment by Alexthw46** [comment]
whoops, i'll cherry pick to another branch so you can pull it without waiting a feature PR
