### ISSUE TITLE
DB Role value too long

### ISSUE THREAD

**Issue by Degik** [belgio99/smartfactory#77]
If I try to register a new user with SpecialtyManufactoryOwner role:

api-1              | INFO:root:[]
db                 | 2024-12-09 11:36:33.129 UTC [42] ERROR:  value too long for type character varying(20)
db                 | 2024-12-09 11:36:33.129 UTC [42] STATEMENT:  INSERT INTO Users (Username, Email, Role, Password, SiteName) VALUES ('max', 'max@smartfactory.com', 'SpecialtyManufactoryOwner', '$2b$12$aaaaaaaaaaaaaaaaeeeeeej1c68oGExAD0ggPUW8BKtyTjJbd9GeG', 'site1') RETURNING UserID;
api-1              | ERROR:root:Exception: value too long for type character varying(20)
api-1              | 
api-1              | INFO:     172.18.0.12:46112 - "POST /smartfactory/register HTTP/1.1" 500 Internal Server Error
router             | 2024-12-09T11:36:36,799 DEBUG [qtp1514969303-108] org.apache.druid.jetty.RequestLog - 172.18.0.16 GET //router:8888/status/health HTTP/1.1 200

With FloorFactoryManager (less 20 char)

api-1              | INFO:root:[]
api-1              | INFO:     172.18.0.12:45144 - "POST /smartfactory/register HTTP/1.1" 201 Created

**Comment by belgio99** [comment]
I think we’re gonna expand the role field to 255

**Comment by belgio99** [comment]
Did it. Keep in mind that you have to delete the volumes and to run the db-init container to see the changes locally
